services:

  postgres:
    image: postgres:16.6
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  web:
    restart: always
    build: ./
    command: bash scripts/start.sh
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  documentation:
    restart: always
    build: ./
    command: "python3 -m mkdocs serve"
    volumes:
      - ./:/app
    ports:
      - "8001:8001"

volumes:
  postgres_data:
