site_name: library_app
site_description: A simple library app
repo_url: https://github.com/soldatov-ss/library-app
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/soldatov-ss">soldatov-ss</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
