[tool.black]
line-length = 120
target-version = ['py312']
include = '.pyi?$'
extend-exclude = '''
/(
  | migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
extend_skip = [".gitignore", ".dockerignore"]
skip = ["migrations"]

[tool.ruff]
line-length = 120
target-version = "py312"
indent-width = 4
lint.ignore = ["E501", "E712", "B904", "C408", "F841"]
lint.exclude = [
    'venv',  '.git',
    '.idea',  '__pycache__',
    'migrations/',  'scripts/'
]
lint.select = [
"E",   # pycodestyle errors
"W",   # pycodestyle warnings
"F",   # pyflakes
"C",   # complexity
"N",   # pep8-naming
"UP",  # pyupgrade
]

[tool.ruff.lint.per-file-ignores]
"init.py" = ["F401"]  # unused imports in init.py
